### ISSUE TITLE
server down?

### ISSUE THREAD

**Issue by ishotjr** [chaossocial/blog#6]
Apologies, but I wasn't sure how to contact anyone other than via GitHub issues; chaos.social appears to be down/not resolving? 💙

**Comment by rixx** [comment]
Please do not use GitHub issues to contact us. There was a planned and announced downtime today.

**Comment by ishotjr** [comment]
Thanks! What's the best way to get in touch? (asking since things seem down again today?) Where are these announcements made? (only in-app one I recall seeing was RE policy updates?) Thanks so much for all that you do! 💙

**Comment by rixx** [comment]
The announcement was made both via the in-app announcement tool and via [@ordnung](https://chaos.social/@ordnung/109439432922286523). We don't maintain an off-site status page and don't plan to, at the moment – chaos.social is still a hobby project for us, and too much undue professionalisation tends to suck the fun out of things.

**Comment by rixx** [comment]
Just to add: when chaos.social seems to be down completely, you can reach us via email at contact@.

**Comment by ishotjr** [comment]
@rixx thank you so much for taking the time to explain all of this! I have set up notifications to ensure I see any announcements from that account. I really appreciate everything that you are doing, and your willingness to help me learn - thanks! 💙
